# Generated by Django 4.1.4 on 2022-12-23 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ria_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ria_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autopark_id', models.CharField(max_length=50)),
                ('damage', models.BooleanField(blank=True, default=False)),
                ('custom', models.BooleanField(blank=True, default=True)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('vin', models.CharField(max_length=25)),
                ('consumption_city', models.FloatField(blank=True)),
                ('consumption_route', models.FloatField(blank=True)),
                ('consumption_combine', models.FloatField(blank=True)),
                ('engine_volume', models.FloatField(blank=True)),
                ('engine_power_hp', models.IntegerField(blank=True)),
                ('engine_power_kw', models.IntegerField(blank=True)),
                ('metallic_color', models.BooleanField(blank=True)),
                ('auctions', models.BooleanField(default=True)),
                ('comments_allowed', models.BooleanField(default=True)),
                ('comments_check', models.BooleanField(default=False)),
                ('video', models.CharField(blank=True, max_length=50)),
                ('doors', models.IntegerField(blank=True)),
                ('seats', models.IntegerField(blank=True)),
                ('spareParts', models.BooleanField(blank=True, default=False)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.body')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ria_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ria_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ria_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ria_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ria_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ria_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ria_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ria_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ria_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=2000)),
                ('ru', models.CharField(max_length=2000)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_connection.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ria_id', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.brand')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.categories'),
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.city'),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.color'),
        ),
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.country'),
        ),
        migrations.AddField(
            model_name='car',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_currency', to='api_connection.currency'),
        ),
        migrations.AddField(
            model_name='car',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.drive'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.fuel'),
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.gearbox'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.carmodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.region'),
        ),
    ]
