# Generated by Django 4.1.4 on 2023-01-26 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('ria_id', models.IntegerField(unique=True)),
                ('autopark_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('ria_id', models.IntegerField(unique=True)),
                ('autopark_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ria_id', models.IntegerField(unique=True)),
                ('autopark_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('ria_id', models.IntegerField(unique=True)),
                ('autopark_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('ria_id', models.IntegerField()),
                ('autopark_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('ria_id', models.IntegerField(unique=True)),
                ('autopark_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=2000)),
                ('ru', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('ria_id', models.IntegerField(unique=True)),
                ('autopark_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('ria_id', models.IntegerField(unique=True)),
                ('autopark_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('ria_id', models.IntegerField(unique=True)),
                ('autopark_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('ria_id', models.IntegerField(unique=True)),
                ('autopark_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('ria_id', models.IntegerField()),
                ('autopark_id', models.IntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.region')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('ria_id', models.IntegerField()),
                ('autopark_id', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autopark_id', models.CharField(max_length=50)),
                ('damage', models.BooleanField(blank=True, default=False)),
                ('custom', models.BooleanField(blank=True, default=True)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('modification', models.CharField(max_length=35)),
                ('mileage', models.IntegerField()),
                ('vin', models.CharField(max_length=25)),
                ('engine_volume', models.FloatField(blank=True)),
                ('engine_power_hp', models.IntegerField(blank=True)),
                ('engine_power_kw', models.IntegerField(blank=True)),
                ('metallic_color', models.BooleanField(blank=True)),
                ('auctions', models.BooleanField(default=True)),
                ('comments_allowed', models.BooleanField(default=True)),
                ('comments_check', models.BooleanField(default=False)),
                ('video', models.CharField(blank=True, max_length=50)),
                ('doors', models.IntegerField(blank=True)),
                ('seats', models.IntegerField(blank=True)),
                ('spare_parts', models.BooleanField(blank=True, default=False)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.body')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.categories')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.city')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.color')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_currency', to='api_connection.currency')),
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_connection.description')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.drive')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.fuel')),
                ('gearbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.gearbox')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.carmodel')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.region')),
            ],
        ),
    ]
