# Generated by Django 4.1.4 on 2023-01-30 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_connection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('event_description', models.CharField(max_length=255)),
                ('event_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.eventcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ria_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='country',
        ),
        migrations.RemoveField(
            model_name='car',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='metallic_color',
        ),
        migrations.AddField(
            model_name='drive',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_connection.categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gearbox',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_connection.categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_connection.description'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AddField(
            model_name='photo',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_connection.car'),
        ),
        migrations.AddField(
            model_name='car',
            name='options',
            field=models.ManyToManyField(related_name='options', to='api_connection.options'),
        ),
    ]
